### ISSUE TITLE
Parametrize menu function to avoid redundancy

### ISSUE THREAD

**Issue by wbigger** [Prometal328/Keyboard-Teacher#13]
There are several functions like this:
https://github.com/Prometal328/Keyboard-Teacher/blob/829cf507f69ac28d2081cdf63c099e91fcfae1c1/KeyboardTeacher/KeyboardTeacher.pde#L36

Consider creating a single function with a param. For example:
```
void menuButton(Button button) {
  if (button.buttonClicked()) {
      delay(100);
      menuOpened = false;
    }
}
```

**Comment by IonutCicio** [comment]
Where should I create this function?

**Comment by wbigger** [comment]
Just replacing the old functions with the new one
