### ISSUE TITLE
Change function and variable names to follow Java naming convention

### ISSUE THREAD

**Issue by wbigger** [Prometal328/Keyboard-Teacher#8]
It is absolutely crucial to follow the naming convention of the language in use, otherwise, it is very difficult to understand what is going on in the code.  Since Processing is based on Java, you must follow the Java style guide. You can find a good guide for naming convention [here](https://en.wikipedia.org/wiki/Naming_convention_(programming)#Java).

As the title says, please change function and variable names in order to follow Java naming convention.

Also interesting but not crucial at the moment are other code style convention, you can consider to have a look to [twitter](https://github.com/twitter/commons/blob/master/src/java/com/twitter/common/styleguide.md#variable-naming) Java style guide.

**Comment by IonutCicio** [comment]
Ok, thanks.
